- hosts: group1
  remote_user: root
  tasks: 
  - name: "echo helloworld"
    shell: echo helloworld
  - name: "echo hostname"
    shell: echo `hostname`
  - name: "write file 1"
    shell: date >> /root/test1.txt