- hosts: uat1
  remote_user: root
  tasks: 
  - name: "echo helloworld"
    shell: echo helloworld
    register: shell_result
  - debug:
      var: shell_result.stdout_lines

  - name: "echo hostname"
    shell: echo `hostname`
    register: shell_result
  - debug:
      var: shell_result.stdout_lines

  - name: "write file 1"
    shell: date >> /root/test1.txt
    register: shell_result
  - debug:
      var: shell_result.stdout_lines

  - name: "Output file 1"
    shell: cat /root/test1.txt
    register: shell_result
  - debug:
      var: shell_result.stdout_lines

  - name: Steve create soft link 1
    file: 
      src: /root/test1.txt 
      dest: /root/test1.ln
      state: link
    register: shell_result
  - debug:
      var: shell_result.stdout_lines
      
  - name: "List file 1"
    shell: ls -lt /root
    register: shell_result
  - debug:
      var: shell_result.stdout_lines
      
  - name: "List file 2"
    shell: 
      chdir: /root
      cmd: ls -lt
  - debug:
      var: shell_result.stdout_lines
      